export enum NotificationRecipientType {
  USER = 'USER',
  COMPANY = 'COMPANY',
}

export enum NotificationSenderType {
  SYSTEM = 'SYSTEM',
  CANDIDATE = 'CANDIDATE',
  COMPANY = 'COMPANY',
}

export enum NotificationType {
  APPLICATION_SUBMITTED = 'APPLICATION_SUBMITTED',
  APPLICATION_STAGE_CHANGED = 'APPLICATION_STAGE_CHANGED',
  APPLICATION_CV_VIEWED = 'APPLICATION_CV_VIEWED',
  COMPANY_VERIFICATION_CHANGED = 'COMPANY_VERIFICATION_CHANGED',
  COMPANY_FOLLOWED_JOB_PUBLISHED = 'COMPANY_FOLLOWED_JOB_PUBLISHED',
  ADMIN_COMPANY_REVIEW_REQUIRED = 'ADMIN_COMPANY_REVIEW_REQUIRED',
  ADMIN_JOB_REVIEW_REQUIRED = 'ADMIN_JOB_REVIEW_REQUIRED',
  ADMIN_JOB_REVISION_REVIEW_REQUIRED = 'ADMIN_JOB_REVISION_REVIEW_REQUIRED',
  ADMIN_USER_RISK_DETECTED = 'ADMIN_USER_RISK_DETECTED',
  ADMIN_SYSTEM_ALERT = 'ADMIN_SYSTEM_ALERT',
}
