import * as Joi from 'joi';

export const validationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'test', 'production').default('development'),
  CV_PARSING_SERVICE_PORT: Joi.number().default(3006),
  DB_HOST: Joi.string().required(),
  DB_PORT: Joi.number().default(5432),
  CV_PARSING_SERVICE_DB_NAME: Joi.string().required(),
  CV_PARSING_SERVICE_DB_USER: Joi.string().required(),
  CV_PARSING_SERVICE_DB_PASS: Joi.string().required(),
  REDIS_URL: Joi.string().uri({ scheme: ['redis', 'rediss'] }).allow('').optional(),
  REDIS_HOST: Joi.string().when('REDIS_URL', {
    is: Joi.string().min(1).required(),
    then: Joi.optional(),
    otherwise: Joi.required(),
  }),
  REDIS_PORT: Joi.number().default(6379),
  INTERNAL_SERVICE_TOKEN: Joi.when('NODE_ENV', {
    is: 'production',
    then: Joi.string().required(),
    otherwise: Joi.string().default('dev-internal-service-token'),
  }),
  GEMINI_API_KEY: Joi.string().allow('').optional(),
  GEMINI_MODEL: Joi.string().default('gemini-3.5-flash'),
  GEMINI_MAX_OUTPUT_TOKENS: Joi.number().default(8192),
  GEMINI_PARSE_RETRY_ATTEMPTS: Joi.number().integer().min(0).max(3).default(0),
  GEMINI_TIMEOUT_MS: Joi.number().default(60000),
  GEMINI_PROVIDER_VERSION: Joi.string().allow('').optional(),
  CV_PARSE_PROVIDER: Joi.string().valid('GEMINI', 'OPENAI').default('GEMINI'),
  CV_PARSE_PERSIST_RAW_PAYLOAD: Joi.boolean().default(false),
  OPENAI_API_KEY: Joi.string().allow('').optional(),
  OPENAI_BASE_URL: Joi.string().uri().default('https://modelapi.vn/v1'),
  OPENAI_MODEL: Joi.string().default('gpt-5.5'),
  OPENAI_MAX_OUTPUT_TOKENS: Joi.number().default(8192),
  OPENAI_TIMEOUT_MS: Joi.number().default(60000),
  OPENAI_LOG_PROVIDER_ERROR_BODY: Joi.boolean().default(false),
  OPENAI_PROVIDER_VERSION: Joi.string().allow('').optional(),
  OPENAI_PERSIST_RAW_PAYLOAD: Joi.boolean().default(false),
  TEMPLATE_DESIGN_MAX_OUTPUT_TOKENS: Joi.number().default(16384),
  TEMPLATE_DESIGN_JOB_TIMEOUT_MS: Joi.number().default(300000),
  CANDIDATE_SERVICE_URL: Joi.string().uri().default('http://localhost:3002'),
  DOCUMENT_STORAGE_SERVICE_URL: Joi.string().uri().default('http://localhost:3009'),
  CV_PARSING_SERVICE_HTTP_TIMEOUT_MS: Joi.number().default(30000),
});
