import * as Joi from 'joi';

export const validationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'test', 'production').default('development'),
  NOTIFICATION_SERVICE_PORT: Joi.number().default(3008),
  DB_HOST: Joi.string().required(),
  DB_PORT: Joi.number().default(5432),
  NOTIFICATION_SERVICE_DB_NAME: Joi.string().required(),
  NOTIFICATION_SERVICE_DB_USER: Joi.string().required(),
  NOTIFICATION_SERVICE_DB_PASS: Joi.string().required(),
  REDIS_HOST: Joi.string().required(),
  REDIS_PORT: Joi.number().default(6379),
  RABBITMQ_URL: Joi.string()
    .uri({ scheme: ['amqp', 'amqps'] })
    .allow('')
    .optional(),
  RABBITMQ_EXCHANGE: Joi.string().default('nexhire.events'),
  SMTP_HOST: Joi.string().allow('').optional(),
  SMTP_PORT: Joi.alternatives().try(Joi.number(), Joi.string().allow('')).optional(),
  SMTP_SECURE: Joi.boolean().optional(),
  SMTP_USER: Joi.string().allow('').optional(),
  SMTP_PASS: Joi.string().allow('').optional(),
  MAILTRAP_SMTP_HOST: Joi.string().default('sandbox.smtp.mailtrap.io'),
  MAILTRAP_SMTP_PORT: Joi.number().default(2525),
  MAILTRAP_SMTP_SECURE: Joi.boolean().default(false),
  MAILTRAP_SMTP_USER: Joi.string().allow('').optional(),
  MAILTRAP_SMTP_PASS: Joi.string().allow('').optional(),
  SMTP_FROM: Joi.string().default('NexHire <noreply@nexhire.vn>'),
  NOTIFICATION_QUEUE_EMAIL_VERIFICATION: Joi.string().default('notification.email.verification'),
  NOTIFICATION_QUEUE_PASSWORD_RESET: Joi.string().default('notification.email.password-reset'),
  NOTIFICATION_QUEUE_IN_APP_APPLICATION: Joi.string().default('notification.in-app.application'),
  FRONTEND_URL: Joi.string().uri().default('http://localhost:5173'),
  FRONTEND_VERIFY_EMAIL_PATH: Joi.string().default('/verify-email'),
  FRONTEND_RESET_PASSWORD_PATH: Joi.string().default('/reset-password'),
  QUEUE_MONITOR_ENABLED: Joi.boolean().default(false),
  QUEUE_MONITOR_INTERVAL_MS: Joi.number().default(60000),
  QUEUE_MONITOR_ALERT_THRESHOLD: Joi.number().default(100),
  QUEUE_MONITOR_ALERT_COOLDOWN_MS: Joi.number().default(900000),
  QUEUE_MONITOR_QUEUES: Joi.string().allow('').optional(),
  QUEUE_MONITOR_TEST_QUEUE: Joi.string().default('queue-monitor.test-backlog'),
  QUEUE_MONITOR_INCLUDE_TEST_QUEUE: Joi.boolean().optional(),
  QUEUE_MONITOR_TEST_MESSAGE_COUNT: Joi.number().optional(),
  QUEUE_MONITOR_TEST_AUTO_CLEANUP_DELAY_MS: Joi.number().optional(),
  QUEUE_MONITOR_TEST_DELETE_QUEUE_DELAY_MS: Joi.number().optional(),
  RABBITMQ_MANAGEMENT_URL: Joi.string().uri().allow('').optional(),
  RABBITMQ_HTTP_URL: Joi.string().uri().allow('').optional(),
  RABBITMQ_MANAGEMENT_VHOST: Joi.string().default('/'),
  RABBITMQ_MANAGEMENT_USER: Joi.string().default('nexhire'),
  RABBITMQ_MANAGEMENT_PASS: Joi.string().default('nexhire'),
  TELEGRAM_BOT_TOKEN: Joi.string().allow('').optional(),
  TELEGRAM_CHAT_ID: Joi.string().allow('').optional(),
});
