export enum CvParseProvider {
  GEMINI = 'GEMINI',
  OPENAI = 'OPENAI',
}

export enum CvParseRequestStatus {
  QUEUED = 'QUEUED',
  PROCESSING = 'PROCESSING',
  SUCCEEDED = 'SUCCEEDED',
  FAILED = 'FAILED',
}

export enum CvParseContext {
  PROFILE_UPDATE = 'PROFILE_UPDATE',
  TEMPLATE_FILL = 'TEMPLATE_FILL',
  MATCHING_APPLICATION = 'MATCHING_APPLICATION',
  MANUAL_REVIEW = 'MANUAL_REVIEW',
}
