export enum JobStatus {
  DRAFT = 'DRAFT',
  PENDING_REVIEW = 'PENDING_REVIEW',
  NEEDS_REVIEW = 'NEEDS_REVIEW',
  SHOULD_REJECT = 'SHOULD_REJECT',
  PUBLISHED = 'PUBLISHED',
  UNPUBLISHED = 'UNPUBLISHED',
  REJECTED = 'REJECTED',
  CLOSED = 'CLOSED',
  EXPIRED = 'EXPIRED',
}

export enum JobRevisionStatus {
  DRAFT = 'DRAFT',
  PENDING_REVIEW = 'PENDING_REVIEW',
  NEEDS_REVIEW = 'NEEDS_REVIEW',
  SHOULD_REJECT = 'SHOULD_REJECT',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum JobModerationRiskLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum JobModerationDecision {
  PENDING_REVIEW = 'PENDING_REVIEW',
  NEEDS_REVIEW = 'NEEDS_REVIEW',
  SHOULD_REJECT = 'SHOULD_REJECT',
}

export enum JobReviewDecision {
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
}
