export const OPENAI_PARSED_RESUME_SCHEMA = {
  type: 'object',
  additionalProperties: false,
  required: ['profile', 'skills', 'experiences', 'educations', 'certifications', 'projects'],
  properties: {
    profile: {
      type: 'object',
      additionalProperties: false,
      required: [
        'fullName',
        'phone',
        'contactEmail',
        'headline',
        'summary',
        'location',
        'portfolioUrl',
        'linkedinUrl',
      ],
      properties: {
        fullName: { type: ['string', 'null'] },
        phone: { type: ['string', 'null'] },
        contactEmail: { type: ['string', 'null'] },
        headline: { type: ['string', 'null'] },
        summary: { type: ['string', 'null'] },
        location: { type: ['string', 'null'] },
        portfolioUrl: { type: ['string', 'null'] },
        linkedinUrl: { type: ['string', 'null'] },
      },
    },
    skills: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        required: ['name', 'level', 'yearsOfExperience'],
        properties: {
          name: { type: 'string' },
          level: { type: ['string', 'null'] },
          yearsOfExperience: { type: ['number', 'null'] },
        },
      },
    },
    experiences: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        required: [
          'companyName',
          'position',
          'employmentType',
          'startMonth',
          'startYear',
          'endMonth',
          'endYear',
          'isCurrent',
          'description',
        ],
        properties: {
          companyName: { type: 'string' },
          position: { type: 'string' },
          employmentType: { type: ['string', 'null'] },
          startMonth: { type: ['number', 'null'] },
          startYear: { type: ['number', 'null'] },
          endMonth: { type: ['number', 'null'] },
          endYear: { type: ['number', 'null'] },
          isCurrent: { type: ['boolean', 'null'] },
          description: { type: ['string', 'null'] },
        },
      },
    },
    educations: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        required: [
          'schoolName',
          'degree',
          'fieldOfStudy',
          'startYear',
          'endYear',
          'isCurrent',
          'description',
        ],
        properties: {
          schoolName: { type: 'string' },
          degree: { type: ['string', 'null'] },
          fieldOfStudy: { type: ['string', 'null'] },
          startYear: { type: ['number', 'null'] },
          endYear: { type: ['number', 'null'] },
          isCurrent: { type: ['boolean', 'null'] },
          description: { type: ['string', 'null'] },
        },
      },
    },
    certifications: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        required: ['name', 'issuer', 'credentialUrl', 'issuedYear', 'description'],
        properties: {
          name: { type: 'string' },
          issuer: { type: ['string', 'null'] },
          credentialUrl: { type: ['string', 'null'] },
          issuedYear: { type: ['number', 'null'] },
          description: { type: ['string', 'null'] },
        },
      },
    },
    projects: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        required: ['name', 'description', 'technologies', 'projectUrl'],
        properties: {
          name: { type: 'string' },
          description: { type: ['string', 'null'] },
          technologies: {
            type: 'array',
            items: { type: 'string' },
          },
          projectUrl: { type: ['string', 'null'] },
        },
      },
    },
  },
} as const;
